// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARadWlGJeR_4A2_NCOK9-Fo6bXVDcFPlw',
    appId: '1:387598634372:web:dbab6acd782084a5f921d1',
    messagingSenderId: '387598634372',
    projectId: 'projectmanagement-2aef4',
    authDomain: 'projectmanagement-2aef4.firebaseapp.com',
    storageBucket: 'projectmanagement-2aef4.appspot.com',
    databaseURL: 'https://projectmanagement-2aef4-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv9eqpDVsk_1_Ee47h0tyRojLbYDElGAw',
    appId: '1:387598634372:android:95b7d4072d0aa1dff921d1',
    messagingSenderId: '387598634372',
    projectId: 'projectmanagement-2aef4',
    storageBucket: 'projectmanagement-2aef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD836XjV0TdBLpQNlPyaW3F0GLWthFPjGQ',
    appId: '1:387598634372:ios:5c8e2e06bc2e7b45f921d1',
    messagingSenderId: '387598634372',
    projectId: 'projectmanagement-2aef4',
    storageBucket: 'projectmanagement-2aef4.appspot.com',
    iosBundleId: 'com.example.projectManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD836XjV0TdBLpQNlPyaW3F0GLWthFPjGQ',
    appId: '1:387598634372:ios:745f8604963684b7f921d1',
    messagingSenderId: '387598634372',
    projectId: 'projectmanagement-2aef4',
    storageBucket: 'projectmanagement-2aef4.appspot.com',
    iosBundleId: 'com.example.projectManager.RunnerTests',
  );
}
